# Generated by Django 4.1.6 on 2023-02-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
